-- Seed initial settings
INSERT INTO public.settings (buy_in, draft_locked, draft_started, draft_completed)
VALUES (25, FALSE, FALSE, FALSE)
ON CONFLICT DO NOTHING;

-- Seed 48 FIFA World Cup teams with flags and codes
INSERT INTO public.teams (name, flag, fifa_code, iso_code) VALUES
('Qatar', '🇶🇦', 'QAT', 'QA'),
('Ecuador', '🇪🇨', 'ECU', 'EC'),
('Senegal', '🇸🇳', 'SEN', 'SN'),
('Netherlands', '🇳🇱', 'NED', 'NL'),
('England', '🇬🇧', 'ENG', 'GB'),
('Iran', '🇮🇷', 'IRN', 'IR'),
('United States', '🇺🇸', 'USA', 'US'),
('Wales', '🇬🇧', 'WAL', 'GB'),
('France', '🇫🇷', 'FRA', 'FR'),
('Australia', '🇦🇺', 'AUS', 'AU'),
('Denmark', '🇩🇰', 'DEN', 'DK'),
('Tunisia', '🇹🇳', 'TUN', 'TN'),
('Germany', '🇩🇪', 'GER', 'DE'),
('Spain', '🇪🇸', 'ESP', 'ES'),
('Costa Rica', '🇨🇷', 'CRC', 'CR'),
('Japan', '🇯🇵', 'JPN', 'JP'),
('Belgium', '🇧🇪', 'BEL', 'BE'),
('Canada', '🇨🇦', 'CAN', 'CA'),
('Morocco', '🇲🇦', 'MAR', 'MA'),
('Croatia', '🇭🇷', 'CRO', 'HR'),
('Saudi Arabia', '🇸🇦', 'KSA', 'SA'),
('Mexico', '🇲🇽', 'MEX', 'MX'),
('Poland', '🇵🇱', 'POL', 'PL'),
('Argentina', '🇦🇷', 'ARG', 'AR'),
('Greece', '🇬🇷', 'GRE', 'GR'),
('Switzerland', '🇨🇭', 'SUI', 'CH'),
('Cameroon', '🇨🇲', 'CMR', 'CM'),
('Brazil', '🇧🇷', 'BRA', 'BR'),
('Ghana', '🇬🇭', 'GHA', 'GH'),
('Uruguay', '🇺🇾', 'URU', 'UY'),
('South Korea', '🇰🇷', 'KOR', 'KR'),
('Portugal', '🇵🇹', 'POR', 'PT'),
('Serbia', '🇷🇸', 'SRB', 'RS'),
('Sweden', '🇸🇪', 'SWE', 'SE'),
('Italy', '🇮🇹', 'ITA', 'IT'),
('Uzbekistan', '🇺🇿', 'UZB', 'UZ'),
('Kyrgyzstan', '🇰🇬', 'KGZ', 'KG'),
('Hong Kong', '🇭🇰', 'HKG', 'HK'),
('Tajikistan', '🇹🇯', 'TJK', 'TJ'),
('Japan Alt', '🇯🇵', 'JP2', 'JP'),
('South Africa', '🇿🇦', 'RSA', 'ZA'),
('Nigeria', '🇳🇬', 'NGA', 'NG'),
('Egypt', '🇪🇬', 'EGY', 'EG'),
('Kenya', '🇰🇪', 'KEN', 'KE'),
('Ethiopia', '🇪🇹', 'ETH', 'ET'),
('Zambia', '🇿🇲', 'ZMB', 'ZM'),
('Zimbabwe', '🇿🇼', 'ZWE', 'ZW'),
('Malawi', '🇲🇼', 'MWI', 'MW'),
('Tanzania', '🇹🇿', 'TZA', 'TZ')
ON CONFLICT DO NOTHING;
